REPO_DIR='./'

# Remote FTP Connection
REMOTE_SERVER_HOST='108.61.157.242'
REMOTE_SERVER_USERNAME='drivepk'
REMOTE_SERVER_PASSWORD='Samsung123$'
REMOTE_SERVER_PORT=21
REMOTE_SERVER_DIR='/gitpython/'

